training_hyperparams:
  data_path: "/home/conradli/SmarterThanBackProp/data/"
  n_epochs : 10
  batch_size_train : 50
  batch_size_test : 100

logging_params:
  save_dir: "./results"
  log_interval : 10

optim_hyperparams:
  learning_rate : 0.01
  momentum : 0.5

model_hyperparams:
  mnist_mlp:
    input_dim: 784
    output_dim: 10 
    activation: "relu"
    layers: [784, 64, 32, 10]